TIDEngine
$domain
You can define root domain if for some reason you have problems with Javascript and/or CSS Cache Files Paths. If you have no problems you can leave it empty. string $domain
$root_cache
Cache directory root path. If you do not change orginal TIDEngine structure, Default : 'cache/' If you have your own structure set path depending of your needs. string $root_cache
$pages_cache
Cached Templates/Pages cache directory name. Default : 'pages/' string $pages_cache
$css_cache
Css cache directory name. Default : 'css/' string $css_cache
$js_cache
Javascript cache directory name. Default : 'javascript/' string $js_cache
$javascript_source
Javascript source files directory path. Default : 'javascript/native/source/' string $javascript_source
$javascript_minified
Javascript minified files directory path. Default : 'javascript/native/minified/' string $javascript_minified
$frameworks_source
Javascript Frameworks source files directory path. Default : 'javascript/frameworks/' string $frameworks_source
$css_source
CSS source files directory path. Default : 'css/' string $css_source
$cache_naming
Templates/Pages cache files unique naming type. string $cache_naming - you can use one of the following name possibilities: md5 - Page/Template cache name is md5 value of template name.sha1 - Page/Template cache name is sha1 value of template name.native - use native templatre names
$cache_name_pre
Cache name prefix implemented for easier data changes check unique value inside brackets. string : Default '(' eg. ()- full Cache separators
$cache_name_post
Cache name sufix implemented for easier data changes check unique value inside brackets. string : Default '(' eg. ()- full Cache separators
$cache_extension
Pages cache extension in use, you can use any type of extension, because Template/Page Cache File just store XHTML code, there are no direct access, they are final data storag, render by TIDEngine. string $cache_extension
$server_caching
Use Server Caching. If this is enabled all Page Components will be processed depending of Settings and Cached on Server Side. Until Page Components do not expire or some of Data are changed TIDEngine will serve Cached. Files for every Page Request. bool $server_caching
$client_caching
Use Client/Browser Caching. If this is enabled on every page request will be checked Cache existance and validity. If Cache files pass checking for individual Cache file will be set 304 Redirect - Not Modified. EG. If you have unique Javascript files for all pages on different pages access will be used same Javascript, CSS files from Browser cache if is valid if not TIDEngine will serve Server Side Cached Files. bool $client_caching
$gzip
Use gzip compression on Page/Template Compress Server Side Cache Files. bool $gzip
$compression_level
Set general compression level for all Cache Files. There are 1-9 - gzip compression levels. fast: 1-4,slower: 5-6 (but better compression),slow: 7-9 (up to 2x faster, best compression) On files under 300K level 4 is good enought. bool $compression_level
$cache_lifetime
Set Cache Life Time in seconds EG. 60 seconds x 60 minutes x 24 hours = one day cache life time. You can set cache lifetime in miliseconds or as string 'permanent' means. EG. 1.minute 1.hour 1.day 1.month 1.year $this->cache_lifetime=array( 'page'=>'1.minute', 'css'=>'1.hour', 'javascript'=>'1.day', 'frameworks'=>'1.month' ); Other possibility is to set one lifetime for all cache files: $this->cache_lifetime='1.month'; or $this->cache_lifetime='permanent'; array $cache_lifetime
$xhtml_code_operations
You can use two types of XHTML Optimization. Indent XHTML code or clean whitespace and combine XHTML code in one lien. string $xhtml_code_operations string : compact - optimize XHTML code and remove whitespace complete XHTML in one lineindent - set XHTML code indentation,false - any value no XHTML manipulation
$xhtml_code_indentation
Set default indentation space only. EG. ' ' string $xhtml_code_indentation
$optimize_css
Use CSS optimization. Clean CSS files and put all code in one line - size reduction. Todoadd CSStidy support bool $optimize_css
bool $optimize_css_gz
Use gzip compression on CSS Cache files. File size reduction.
$compact_css
Combine all CSS files in one unique file. CoReduces the number of HTTP requests. bool $compact_css
$css_file_name
Set file name for combined file. If we combine all CSS files combined CSS file name.Todo CSS Files versioning if we need it. bool $css_file_name
$css_ext
Set default CSS extension. Look sily but we need that for Safari gzip bug. Safari acceprt default extension for gzipped files in format .css.gz or .css.gz.css* string $css_ext
$optimize_javascript
Use Javascript optimization. Clean Javascript files and put all code in one line - size reduction. This means we will use some of external Javascript Packers. bool $optimize_javascript
$combine_all_javascript
Combine all Javascript and Javscript Frameworks files in one file. If we use this option all Javascript files will be treated as native Javascript files. Compress Javascript files - Reduces the number of HTTP requests. bool $combine_all_javascript
$compact_javascript
Combine all Javascript files in two files, one for native Javascript source files and other for Javscript Frameworks Files. Compress Javascript files - Reduces the number of HTTP requests. If $combine_all_javascript are enabled this setting will have no effects. bool $compact_javascript
bool $optimize_javascript_gz
Use gzip compression on Javascript Cache files . Compress Javascript files - size reduction.
$packer
Optimize Javascript files, by using some of build in Javascript Packers. You must realize that every time you use Javascript Optimization you will have high server load, and long response time. Workarround for this is to create minified versions of Javascript Frameworks files. Or to create them on Localhost. By default TIDEngine checks if there are minified version of Javascript files during first time load and if they do not exist create them, so you will have high Server load just once during creation of minified version of Javascript files. When you have minified version of Javascript files there are no high Server load. If you do not have Javascript changes you could just: set $cache_lifetime = 'permanent'; andchange .httacces file lines 1 month to 1 year: ExpiresByTypeapplication/javascript"accessplus1month" ExpiresByTypeapplication/x-javascript"accessplus1month" string $packer string : packer - PHP 5 ported version of Dean Edwards Packerjsmin - JSmin packer PHP ported version of Dean Edwards JSminjshrink - JShrink-0.2.class.php hosted on Google Codejsminplus - one more port of Dean Edwards JSminnative - TIDEngine native compressor based on regular Expressions - Not finished.
Referenced by Packer.
$js_ext
Set default Javascript extension. Look sily but we need that for Safari gzip bug. Safari acceprt default extension for gzipped files in format .js.gz.js or .css.gz.css* string $js_ext
$javascript_combined
New combined javascript file name. When we use combinig all Javascript files into one. string $javascript_combined
$javascript_filename
New combined javascript file name. When we combine native Javascript files ad one Cache file and Frameworks as second.. string $javascript_filename
$framework_filename
New combined frameworks file name. When we combine native Javascript files ad one Cache file and Frameworks as second.. string $framework_filename
$frameworks_type
If Framework type in use. string $frameworks_type string : source - If we use source - no minified versions of Javascript will be created.minified - If we use minified - minified versions of all Javascript will be created.
array $shortcodes
Shortcodes array defined for specific template
num $data_changes_check
Data send to TempEngine md5 for checking for changes.
num $modification_time
Cache file modification time.
num $template_id
Template file name/id.
Referenced by check_cache, clear_cache.
$configuration_file
Include external cofiguration file. If you leave empty this path, you must set settings when you init Class. If there are no defined settings default settings will be used. default path: 'TIDEngine/configuration/config.php' string $configuration_file
$meta_spec
For meta tags spec. array $meta_spec
$debug_meta
Use SEO Optimization Adviser/Debugger. bool $debug_meta
__construct()
Class constructor. Detailed instructions inside Class inline comments
References caculate_lifetime, check_browser_set_extension, include_packer.
check_cache($_data, $template_path, $template_id, $elements, $caching)
Checks for Cache existance, Cache file validity and Cache expiration time. Detailed instructions inside Class inline comments array $_data - Data to be phrased to template shortcodes array key = SHORTCODE, array value = DATA. string $template_path - Path to template file string $template_id - Template name array $elements - Extra elements we need to include, default header, body and footer. bool $caching - Do we use caching for specific template
References $template_id, create_minified, display, getRequestHeaders, shortcodes.
create_minified($file)
Create minified version of source Javascript files string $file
References js_packers.
Referenced by check_cache.
display($file_path, $cache=false, $elements=false)
Display page and|or Create Cache file. string $file_path - path to template or cache file. bool $cache - we need to create cache file controll variable bool $elements - page elements.
References clean_file, clean_html_code, shortcodes.
Referenced by check_cache.
shortcodes($data)
shortcodes($data) - Set shortcodes for template array $data - defined shortcodes that must be phrased to template
References css_data, javascript_data, meta_data.
Referenced by check_cache, css_data, display, javascript_data, meta_data.
css_data($data)
Set CSS head data. CSS files paths array $data - CSS files paths
References optimize_css, shortcodes.
Referenced by shortcodes.
optimize_css($files)
Optimize css files string $files - CSS file content
References clean_file, gzip_data.
Referenced by css_data.
javascript_data($data, $type)
Set Javascript/Javascript Frameworks array $data - Javascript files string $type - frameworks or regular Javascript files
References optimize_javascript, shortcodes.
Referenced by shortcodes.
optimize_javascript($files, $type)
Optimize Javascript files array $files string $type string $js - Links
References gzip_data, js_packers.
Referenced by javascript_data.
js_packers($file_content)
Optimize Javascript data with different Packers. string $file_content string $optimized_file
References JShrink, JSmin, JSminplus, Packer.
Referenced by create_minified, optimize_javascript.
include_debugger()
Include SEO Optimization Adviser/Debugger Class. TodoUse SEO Optimization Adviser/Debugger.
include_packer()
Include defined packer Class in use.TodoNative Class packer.
Referenced by __construct.
Packer($js_file)
Packer - PHP 5 ported version of Dean Edwards Packer string $js_file
References $packer.
Referenced by js_packers.
JSmin($js_file)
JSmin - JSmin packer PHP ported version of Dean Edwards JS string $js_file
Referenced by js_packers.
JShrink($js_file)
JShrink - JShrink-0.2.class.php hosted on Google Code string $js_file
Referenced by js_packers.
JSminplus($js_file)
JSminPlus - one more port of Dean Edwards JSmin string $js_file
Referenced by js_packers.
gzip_data($data)
If enabled gzip cache files string $data
Referenced by optimize_css, optimize_javascript.
save_data($data, $path, $modifiers=false)
Save cache files string $data - file data string $path - Cache File Path bool $modifiers - overwrite, append data to file.
meta_data($data)
Set head Page Title and Meta Tags. array $data
References shortcodes.
Referenced by shortcodes.
fix_newlines_for_clean_html($fixthistext)
Function to seperate multiple tags one line. Credits to orginal author. string $fixthistext
Referenced by clean_html_code.
clean_html_code($uncleanhtml)
Indent XHTML output code $this->xhtml_code_indentation. Credits to orginal author. string $uncleanhtml string implode("\n", $cleanhtml_array)
References fix_newlines_for_clean_html.
Referenced by display.
clear_cache($template_id=false)
Manualy clear cache. string $template_id
References $template_id.
clean_file($content)
Remove white space, comments etc.
Referenced by display, optimize_css.
browser_info($agent=null)
Code taken php.org and slitly adapted. Lightweight alternative for Browscap. string null $agent - string to check if we have access by defined agent
Referenced by check_browser_set_extension.
getRequestHeaders()
Get Client Browser headers data.
Referenced by check_cache.
caculate_lifetime()
Calculate Cache Life Time in miliseconds
Referenced by __construct.
check_browser_set_extension()
Workarround for Safari problem with gzipped content we need other type of compressed cache files extensions. As some hosting companies do not support get_browser function I was thinking that best solution is native Browscap class - first time load this class will update all data in cache file. eg. Other browsers .css.gz and .js.gz Safari css.gz.css and js.gz.js infact this is not strict rule you can set any kind of extension just not to be .gz eg. js.gz.xyz and css.gz.xyz - this will work without problem. Uncomment this line :$check_browser = new Browscap($this->Browscap_cache); $browser = $check_browser->getBrowser(null, false); $this->browser = $browser->Browser;and$this->Browscap_cache = $this->root_cache . 'Browscap';also comment this two lines of code:$browser = $this->browser_info(); $this->browser = ucfirst($browser[0]);
References browser_info.
Referenced by __construct.