.TH "TIDEngine/core/TIDEngine.php" 3 "Sat Apr 30 2011" "Version 1.0" "TIDEngine API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIDEngine/core/TIDEngine.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTIDEngine\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TIDEngine API from the source code.
