.TH "todo" 3 "Sat Apr 30 2011" "Version 1.0" "TIDEngine API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- .TH "todo" 3 "Sat Apr 30 2011" "Version 1.0" "TIDEngine API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \-  
.IP "\fBGlobal \fBTIDEngine::$css_file_name\fP \fP" 1c
- CSS Files versioning if we need it. 
.PP
.PP
 
.IP "\fBGlobal \fBTIDEngine::$optimize_css\fP \fP" 1c
add CSStidy support
.PP
.PP
 
.IP "\fBGlobal \fBTIDEngine::include_debugger\fP() \fP" 1c
Use SEO Optimization Adviser/Debugger.
.PP
.PP
 
.IP "\fBGlobal \fBTIDEngine::include_packer\fP() \fP" 1c
Native Class packer. 
.PP
.PP
 
.IP "\fBGlobal \fBTIDEngine::meta_data\fP($data) \fP" 1c
$this->debug_meta will be part of TIDEbugger Class 
.PP
.PP
 
.IP "\fBGlobal \fBTIDEngine::optimize_css\fP($files) \fP" 1c
Add CSSTidy support and some other Libaries 
.PP

